# frozen_string_literal: true

WATCH_PATTERN = %r{^src/.*}.freeze

run_build = proc { system('bundle exec apogee build') }

guard :yield, { run_on_modifications: run_build } do
  watch(WATCH_PATTERN)
end

guard 'livereload' do
  watch(WATCH_PATTERN)
end
